name: Run tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.version }}
      - name: Install dependencies
        run: |
          python -m pip install poetry ruff

          python -m venv venv
          source venv/bin/activate

          poetry install
      - name: Ruff check
        run: |
          source venv/bin/activate

          ruff check
      - name: Run tests
        run: |
          source venv/bin/activate

          pytest --cov-fail-under=100
      - name: Run example/getting_started
        run: |
          cd examples/getting_started

          python -m venv venv
          source venv/bin/activate

          poetry install
          dagster dev &

          sleep 10
      - name: Run example/advanced_usage
        run: |
          cd examples/advanced_usage

          python -m venv venv
          source venv/bin/activate

          poetry install
          dagster dev &

                sleep 10
