name: Run tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install poetry ruff

          python -m venv venv
          source venv/bin/activate

          poetry install
      - name: Ruff check
        run: |
          source venv/bin/activate

          ruff check
      - name: Run tests
        run: |
          source venv/bin/activate

          pytest --cov-fail-under=100
      - name: Run example
        run: |
          cd example

          python -m venv venv
          source venv/bin/activate

          poetry install
          dagster dev &

          sleep 20
